version: "3.7"
services:
  trojan:
    image: trojangfw/trojan
    restart: always
    container_name: ds-trojan
    volumes:
      - /etc/localtime:/etc/localtime
      - ./trojan:/config
      - ./caddy/certify:/root/.caddy
    depends_on:
      - caddy
    ports:
      - "443:443"
  caddy:
    image: caddy
    restart: always
    container_name: ds-caddy
    working_dir: /var/www/html
    volumes:
      - /etc/localtime:/etc/localtime
      - ./wwwroot:/usr/share/caddy
      - ./caddy/conf/Caddyfile:/etc/Caddyfile
      - ./caddy/data:/data
    ports:
      - "80:80"
      - "8443:8443"
