version: "3.7"
services:
  trojan:
    image: trojangfw/trojan
    restart: always
    container_name: ds-trojan
    volumes:
      - /etc/localtime:/etc/localtime
      - ./trojan:/config
      - ./caddy/certify:/root/.caddy
    depends_on:
      - caddy
    ports:
      - "443:443"
  caddy:
    image: abiosoft/caddy:php
    restart: always
    container_name: ds-caddy
    working_dir: /var/www/html
    volumes:
      - /etc/localtime:/etc/localtime
      - ./wwwroot:/var/www/html
      - ./caddy/conf/Caddyfile:/etc/Caddyfile
      - ./caddy/certify:/root/.caddy
    ports:
      - "80:80"
      - "8443:8443"
  mysqldb:
    #image: mysql:5.6.46
    image: daocloud.io/mysql:5.7.24
    restart: always
    container_name: ds-mysql
    volumes:
      - /etc/localtime:/etc/localtime
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
