version: "3.7"
services:
  trojan:
    image: trojangfw/trojan
    restart: always
    container_name: ds-trojan
    #network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime
      - ./trojan:/config
      - ./caddy/data:/data
    ports:
      - "443:443"
  speedtest:
    image: adolfintel/speedtest
    restart: always
    container_name: ds-speedtest
    environment:
      - MODE=standalone
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - "81:80"
  caddy:
    image: caddy
    restart: always
    container_name: ds-caddy
    working_dir: /var/www/html
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime
      - ./wwwroot:/var/www/html
      - ./caddy/conf/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    ports:
      - "80:80"
      - "8443:8443"
